### ISSUE TITLE
Support for Ubuntu 20.04.4 LTS

### ISSUE THREAD

**Issue by Industry-Standard** [LiaScript/LiaScript-DevServer#2]
Is Ubuntu supported? When I install LiaScript-DevServer and access the webpage, I get this: 

```
Error: Failed to lookup view "main" in views directory "views"
    at Function.render (/usr/local/lib/node_modules/@liascript/devserver/node_modules/express/lib/application.js:580:17)
    at ServerResponse.render (/usr/local/lib/node_modules/@liascript/devserver/node_modules/express/lib/response.js:1017:7)
    at /usr/local/lib/node_modules/@liascript/devserver/dist/index.js:122:13
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/@liascript/devserver/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/local/lib/node_modules/@liascript/devserver/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/local/lib/node_modules/@liascript/devserver/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/@liascript/devserver/node_modules/express/lib/router/layer.js:95:5)
    at /usr/local/lib/node_modules/@liascript/devserver/node_modules/express/lib/router/index.js:281:22
    at param (/usr/local/lib/node_modules/@liascript/devserver/node_modules/express/lib/router/index.js:360:14)
    at param (/usr/local/lib/node_modules/@liascript/devserver/node_modules/express/lib/router/index.js:371:14)
```

I've tested with multiple versions of nodejs / npm but they behave similarly:

```
user@ubusrv2004-adapt:~/liascript$ node --version
v16.14.2
user@ubusrv2004-adapt:~/liascript$ npm --version
8.6.0
user@ubusrv2004-adapt:~/liascript$ liadev --version
DevServer: 1.0.5
LiaScript: 0.10.7
user@ubusrv2004-adapt:~/liascript$ cat ./test.md
---
customTheme: "css/presentation"
title: "Course Title"
subtitle: "Lesson # - Lesson Title"
---

::: vscode-only

# Course Title

## Lesson # - Lesson Title

---

:::

## Objectives

- First Objective
- Second Objective
- Third Objective

note: Any paragraph that starts with "note:" at the beginning of the line will be added to the instructor notes.

---

## First Content Slide

This is the first content slide in the presentation. Individual slides are surrounded by horizontal rule markers (---)

---

## Second Content Slide

![all rights reserved](media/logo.png)

More new content.

--

### Sub Content Slide 1

Use sub content when you have a series of slides on the same topic. While horizontal slide transitions are done with three hyphens (---), sub content transitions vertically with double hyphens (--)

--

### Sub Content Slide 2

More stuff about this topic.

Yes, even more stuff.

---

## Summary

Here's what we discussed:

- Point 1
- Point 2
- Point 3
user@ubusrv2004-adapt:~/liascript$ liadev
 _     _       ____            _       _
| |   (_) __ _/ ___|  ___ _ __(_)_ __ | |_
| |   | |/ _` \___ \ / __| '__| | '_ \| __|
| |___| | (_| |___) | (__| |  | | |_) | |_
|_____|_|\__,_|____/ \___|_|  |_| .__/ \__|
                                |_|

📡 starting server
   - local:           http://localhost:3000
   - on your network: 192.168.206.181
✨ hit Ctrl-c to close the server
Error: Failed to lookup view "main" in views directory "views"
    at Function.render (/usr/local/lib/nodejs/node-v16.14.2-linux-x64/lib/node_modules/@liascript/devserver/node_modules/express/lib/application.js:580:17)
    at ServerResponse.render (/usr/local/lib/nodejs/node-v16.14.2-linux-x64/lib/node_modules/@liascript/devserver/node_modules/express/lib/response.js:1017:7)
    at /usr/local/lib/nodejs/node-v16.14.2-linux-x64/lib/node_modules/@liascript/devserver/dist/index.js:122:13
    at Layer.handle [as handle_request] (/usr/local/lib/nodejs/node-v16.14.2-linux-x64/lib/node_modules/@liascript/devserver/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/local/lib/nodejs/node-v16.14.2-linux-x64/lib/node_modules/@liascript/devserver/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/local/lib/nodejs/node-v16.14.2-linux-x64/lib/node_modules/@liascript/devserver/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/local/lib/nodejs/node-v16.14.2-linux-x64/lib/node_modules/@liascript/devserver/node_modules/express/lib/router/layer.js:95:5)
    at /usr/local/lib/nodejs/node-v16.14.2-linux-x64/lib/node_modules/@liascript/devserver/node_modules/express/lib/router/index.js:281:22
    at param (/usr/local/lib/nodejs/node-v16.14.2-linux-x64/lib/node_modules/@liascript/devserver/node_modules/express/lib/router/index.js:360:14)
    at param (/usr/local/lib/nodejs/node-v16.14.2-linux-x64/lib/node_modules/@liascript/devserver/node_modules/express/lib/router/index.js:371:14)
```

**Comment by andre-dietrich** [comment]
Hi, @Industry-Standard ... I just uploaded a new version could you try this one out? 1.0.6-0.10.8

Just uninstall the devserver and install it again ... If you run the command below, you should get the following output ...

``` bash
$ liadev -v
DevServer: 1.0.6
LiaScript: 0.10.8
```

Can you try out the devserver again? I hope the problem is gone now ... I did a parcel update and some npm audit fix, which caused this error. I tested only the build and it worked, now I did also test the npmjs install and it worked locally ...

Regards

**Comment by Industry-Standard** [comment]
That did not work - same thing again generates the following error:
```
user@ubusrv2004-adapt:~/course$ liadev
 _     _       ____            _       _
| |   (_) __ _/ ___|  ___ _ __(_)_ __ | |_
| |   | |/ _` \___ \ / __| '__| | '_ \| __|
| |___| | (_| |___) | (__| |  | | |_) | |_
|_____|_|\__,_|____/ \___|_|  |_| .__/ \__|
                                |_|

📡 starting server
   - local:           http://localhost:3000
   - on your network: 192.168.206.181
✨ hit Ctrl-c to close the server
Error: Failed to lookup view "main" in views directory "/home/andre/Workspace/Projects/Freinet/liascript-devserver/views"
    at Function.render (/usr/local/lib/node_modules/@liascript/devserver/node_modules/express/lib/application.js:580:17)
    at ServerResponse.render (/usr/local/lib/node_modules/@liascript/devserver/node_modules/express/lib/response.js:1017:7)
    at /usr/local/lib/node_modules/@liascript/devserver/dist/index.js:121:13
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/@liascript/devserver/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/local/lib/node_modules/@liascript/devserver/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/local/lib/node_modules/@liascript/devserver/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/@liascript/devserver/node_modules/express/lib/router/layer.js:95:5)
    at /usr/local/lib/node_modules/@liascript/devserver/node_modules/express/lib/router/index.js:281:22
    at param (/usr/local/lib/node_modules/@liascript/devserver/node_modules/express/lib/router/index.js:360:14)
    at param (/usr/local/lib/node_modules/@liascript/devserver/node_modules/express/lib/router/index.js:371:14)
```
 
Looks like there might be some local directory issues?

`Error: Failed to lookup view "main" in views directory "/home/andre/Workspace/Projects/Freinet/liascript-devserver/views"`

I'm going to try this on another machine and see if it's just a local environment thing. 

**Edit** - I got the same issue on another machine, but I think that _/home/andre_ path may be something introduced in the latest version that's a different issue.

**Comment by andre-dietrich** [comment]
Ok ... Sorry for that, It should be fixed now ... I had to add a target "node 14" to the new parcel build, so that the compiler does not replace `__dirname` by a static value, like the path on my machine but instead to use the directory of where the app is installed ...

Let me know if it is solved ;-)

**Comment by Industry-Standard** [comment]
Yes! 1.0.8 works as expected! 

Thank you very much for such a quick resolution!

I did notice that when I accessed the webpage from another computer while it was running, links replace the IP address with localhost, so the links 404. I don't think the intent is to use this on a separate computer than the devserver host though , so I'm using the software in an unintended way. 

Thanks again for the fix - I'm looking forward to playing with liascript.

**Comment by andre-dietrich** [comment]
@Industry-Standard ... I am glad it is working, we hope you have fun with it creating content ...

yes localhost is set by default, but you can rename this with `--hostname` or `-n` and add the name of your server or simply use your local IP, then all appearances of localhost will be replaced by this name ...

But you can also give the liascript-exporter a try ... it should, if it works correctly, also export to self-contained web sites. The problem with the dev-server is, that it does not store state within the browsers indexeddb. Within the exporter, you can force the usage of indexeddb via the option `--web-indexeddb` ...

Regards ...
